[package]
name = "Dirshot"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
rfd = "0.15.3"
rusqlite = { version = "0.36.0", features = ["bundled"] }
sha256 = "1.6.0"
zstd = "0.13.3"
